void get_block(double *A, double *B, int n, int m, int l, int i, int j, int real);
void put_block(double *A, double *B, int n, int m, int l, int i, int j, int real);
void block_mult_block(double *a, double *b, double *c, int m, int n, int l, int real);
void block_minus_block(double *a, double *b, double *c, int m, int n, int real);
void matrix_mult_matrix(double *a, double *b, double *c, int n, int N);
void residual(double *a, double *b, double *c, int n, int N, int q, int p, pthread_barrier_t *barrier);
void subtraction(double *a, double *e, int i, int n);
int division(double *a, double *e, double *x, double *y, double *z, int i, int n, int m, int l, int k, int q, int p, double *h, double z1);
void put_block_E(double *A, int m, int l);
void answer(double *a, double *e, int n);
void answer(double *a, double *e, double *x, double *y, double *z, int i, int n, int m, int l, int k, int q, int p);
int solve(double *a, double *e, int n);
double norm_matrix(double*a, int n);
int read_array(double *a, const char *filename, int m, int n);
int solve1(double *a, double *e, int n, int m, double z1);
void answer1(double *a, double *e, int n, int m);
int division1(double *a, double *e, int i, int n, double z, int m, double z1);
void subtraction1(double *a, double *e, int i, int n, int m);
double norm_matrix1(double *a, int n, int m);
int f(int i, int q, int p);
void print(double *a, int m, int l, int real);
int solve(double *a, double *b, double *x, double *y, double *z, double *h, double *buf, int n, int m, int k, int l, int max_cols, double z1);
double norm_matrix(double *a, int n, int m, int max_cols);
double norm_matrix_q(double *a, int n, int m, int max_cols);
void subtraction(double *a, double *b, double *x, double *y, double *z, double *h, double *buf, int n, int m, int l, int k, int max_cols, int i, int local_ff);
void answer(double *a, double *b, double *x, double *y, double *z, double *h, double *buf, int n, int m, int l, int k, int max_cols, int j);
inline void block_plus_block(double *a, double *b, double *c, int m, int n, int real);
double residual(double *a, double *b, double *r, double *x, double *y, double *z, double *h, int n, int m, int k, int l, int max_cols);
